@baseUrl = http://localhost:3000
### POST /login
# @name login
POST {{baseUrl}}/v1/api/auth/login HTTP/1.1
Content-Type: application/json

{
  "username": "51900427",
  "password": "123456"
}

### POST /logout
@authToken = {{login.response.body.token}}
# @name logout
POST {{baseUrl}}/v1/api/auth/logout HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{authToken}}

### GET /test 
GET {{baseUrl}}/v1/api/users/test HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
	"username": "51900125"
}

### Add tuition bill
POST {{baseUrl}}/v1/api/tuition-bill/add-tuition-bill HTTP/1.1
Content-Type: application/json

{
	"username": "51900427",
	"tuition": "1000000",
	"paid": "0"
}

### pay-tuition
# @name payTuition
POST {{baseUrl}}/v1/api/users/pay-tuition HTTP/1.1
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
	"username": "51900129"
}

### cancel transaction 
GET {{baseUrl}}/v1/api/users/cancel-transaction HTTP/1.1
Authorization: Bearer {{authToken}}

### get otp
GET {{baseUrl}}/v1/api/users/get-otp HTTP/1.1
Authorization: Bearer {{authToken}}

### verify otp
POST {{baseUrl}}/v1/api/users/verify-otp HTTP/1.1
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
	"otp": "659936"
}


